# .github/workflows/deploy.yaml
name: Deploy Flask App to Linode

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set Up Python
      uses: actions/setup-python@v4  # Updated to v4
      with:
        python-version: '3.8'

    - name: Activate Virtual Environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env File in ElectionClockEnvironment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IPV4 }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSHKEY }}
        script: |
          mkdir -p /home/deployuser/web/ElectionClockEnvironment
          echo "keyOPENAI=${{ secrets.keyOPENAI }}" > /home/deployuser/web/ElectionClockEnvironment/.env
          echo "AUTHME=${{ secrets.AUTHME }}" >> /home/deployuser/web/ElectionClockEnvironment/.env
          echo "AUTHME=${{ secrets.AUTHME }}" >> $GITHUB_ENV
          echo "id_KEIKO=${{ secrets.id_KEIKO }}" >> /home/deployuser/web/ElectionClockEnvironment/.env
          echo "DEBUG_MODE=${{ secrets.DEBUG_MODE }}" >> /home/deployuser/web/ElectionClockEnvironment/.env

    - name: SSH and Deploy to Linode
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IPV4 }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd /home/deployuser/web/ElectionClock/
          git checkout
          git pull origin main
          sudo systemctl daemon-reload
          sudo systemctl restart gunicorn
          sudo systemctl status gunicorn

    - name: Clean Up Post-Deployment
      run: echo "Deployment Complete and Services Restarted"
