name: Deploy Flask App to Linode

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run:
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Activate Virtual Environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: SSH and Deploy to Linode
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IPV4 }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd /home/deployuser/web/ElectionClock/
          git pull origin main
          sudo systemctl daemon-reload
          sudo systemctl restart gunicorn
          sudo systemctl status gunicorn
    - name: Clean Up Post-Deployment
      run: echo "Deployment Complete and Services Restarted"

